import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "zeanXBT | AI × Web3 × Future",
  description:
    "Where AI meets cinema. Short films, visual stories, and experimental content — fully generated by Artificial Intelligence.",
  keywords: ["AI Video", "Web3", "zeanXBT", "AI Creator", "Generative AI", "AI Cinema"],
  openGraph: {
    title: "zeanXBT | AI × Web3 × Future",
    description:
      "Where AI meets cinema. Short films, visual stories, and experimental content — fully generated by AI.",
    type: "website",
    url: "https://zeanxbt.com",
  },
  twitter: {
    card: "summary_large_image",
    title: "zeanXBT | AI × Web3 × Future",
    description:
      "Where AI meets cinema. Short films, visual stories, and experimental content — fully generated by AI.",
    creator: "@zeanXBT",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#0a0a0f] text-[#e8e8ed]">
        {children}
      </body>
    </html>
  );
}
